@FeedbackAPI_HostAddress = http://localhost:5048

GET {{FeedbackAPI_HostAddress}}/api/feedback
Accept: application/json

###

POST {{FeedbackAPI_HostAddress}}/api/feedback/submit
Content-Type: application/json

{
  "customerId": 1,
  "feedbackText": "The onboarding process was clear, but response times from support could be faster."
}
